### ISSUE TITLE
whisper ppg

### ISSUE THREAD

**Issue by MaxMax2016** [unilight/s3prl-vc#1]
sorry, 看错了，您只是使用了whisper的上采样~~~

**Comment by unilight** [comment]
@MaxMax2016 thank you for the comment! 我看了一下您的projects，非常的感興趣呢！我個人在目前的recipe用whisper PPG的經驗上，因為一個目標語者只有70句訓練資料（大約五分鐘），不知道為什麼完全學習不起來，產生不出有意義的語句。但我看您的好幾個project都有成功訓練起來，個人猜想是不是因為您的學習資料用得比較多，比較有辦法去使用whisper PPG呢？這方面還請您分享一下！

**Comment by MaxMax2016** [comment]
我使用的是whisper的audio encoder的输出，不是audio encoder的浅层网络输出。

**Comment by MaxMax2016** [comment]
确实五分钟太少了，需要在合适数量的语料上面确定方案的正确性，然后再尝试数量较少的训练语料。抱歉我老是看错。
