### ISSUE TITLE
How to generate conf/f0.yaml

### ISSUE THREAD

**Issue by tan90xx** [unilight/s3prl-vc#5]
Hi, thank you for such an amazing project!

I am unsure how to generate the conf/f0.yaml file. Is there any difference between all setting to defaults (f0min=40, f0max=500) or per-speaker settings?

**Comment by unilight** [comment]
Hi @tan90xx,

To answer your first question, you can try to use `s3prl_vc/bin/create_histogram.py`. The code should be self-contained, but if you have problems executing it, please let me know.
For your second question, the f0 range is mainly used for better WORLD feature extraction during MCD evaluation, so setting it to default will not hurt the model performance.

Hope this helps!

**Comment by tan90xx** [comment]
Thank you so much!
