### ISSUE TITLE
Guidance Needed for Training a Custom Vocoder Model

### ISSUE THREAD

**Issue by PAAYAS** [unilight/s3prl-vc#6]
Hello @unilight,
I have been using the `hifigan_vctk+vcc2020` vocoder model but am not satisfied with the quality. I would like to train my own vocoder model and need guidance on how to do so. Could you please provide guidance on how to train a custom vocoder model? Any steps, resources, or tips would be greatly appreciated.

Thank you!

**Comment by unilight** [comment]
@PAAYAS I used the ParallelWaveGAN repo to train the vocoders. To train a new vocoder for your own dataset, you can refer to the instructions here: https://github.com/kan-bayashi/ParallelWaveGAN/tree/master/egs#how-to-make-the-recipe-for-your-own-dateset. It should be quite simple.
